moveing to util
Signed-off-by: Gaetan Semet <gaetan@xeberon.net>

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -107,39 +107,12 @@ if [[ -e .Buildfile ]]; then
     cat .Buildfile
 
     (
+        # Fail fast and fail hard.
+        set -eo pipefail
 
-        shopt -s extglob
+        APP_DIR='/app'
 
-        # Does some serious copying.
-        deep-cp() {
-            declare source="$1" target="$2"
-
-            mkdir -p "$target"
-
-            # cp doesn't like being called without source params,
-            # so make sure they expand to something first.
-            # subshell to avoid surprising caller with shopts.
-            (
-                shopt -s nullglob dotglob
-                set -- "$source"/!(tmp|.|..)
-                [[ $# == 0 ]] || cp -a "$@" "$target"
-            )
-        }
-
-        # Does some serious moving.
-        deep-mv() {
-            deep-cp "$1" "$2"
-            deep-rm "$1"
-        }
-
-        # Does some serious deleting.
-        deep-rm() {
-            # subshell to avoid surprising caller with shopts.
-            (
-                shopt -s dotglob
-                rm -rf "$1"/!(.curlrc|.netrc|tmp|.|..)
-            )
-        }
+        echo "-----> APP_DIR=$APP_DIR"     # /app/
         echo "-----> BIN_DIR=$BIN_DIR"     # /tmp/buildpackgxoEQ/bin
         echo "-----> ROOT_DIR=$ROOT_DIR"   # /tmp/buildpackgxoEQ
         echo "-----> BUILD_DIR=$BUILD_DIR" # /tmp/build_57c17093de9cac714bf607cc0827c297/Stibbons-Squirrel-1c5b6d9
@@ -147,9 +120,10 @@ if [[ -e .Buildfile ]]; then
         echo "-----> ENV_DIR=$ENV_DIR"
         echo "-----> SUB_DIR=$SUB_DIR"     # backend
 
-        APP_DIR='/app'
-
         bpwatch start compile
+
+        # Syntax sugar.
+        source $BIN_DIR/utils
 
         # Copy Anvil app dir to temporary storage...
         bpwatch start anvil_appdir_stage
